version: "3.7"
services:
    wake-up-computer:
        build:
            context: src
            dockerfile: WakeUpComputer/Dockerfile
    sokrates:
        build:
            context: src/Sokrates
            dockerfile: Dockerfile
        volumes:
            - ${SOKRATES_CLIENT_CERTIFICATE_PATH}:/data/client-certificate.pfx
        environment:
            CLIENT_CERTIFICATE_PATH: /data/client-certificate.pfx
            CLIENT_CERTIFICATE_PASSPHRASE: ${SOKRATES_CLIENT_CERTIFICATE_PASSPHRASE}
    untis:
        build:
            context: src
            dockerfile: Untis/Dockerfile
        volumes:
            - ${UNTIS_GPU002_FILE_PATH}:/data/GPU002.txt
        environment:
            GPU002_FILE_PATH: "/data/GPU002.txt"
    final-theses:
        build:
            context: src
            dockerfile: FinalTheses/Dockerfile
        volumes:
            - ${FINAL_THESES_MENTORS_FILE_PATH}:/data/mentors.csv
        environment:
            MENTORS_FILE_PATH: "/data/mentors.csv"
    photo-library:
        build:
            context: src
            dockerfile: PhotoLibrary/Dockerfile
        volumes:
            - ${PHOTO_LIBRARY_TEACHER_PHOTOS_DIRECTORY}:/data/teacher-photos
        environment:
            TEACHER_PHOTOS_DIRECTORY: "/data/teacher-photos"
    aad:
        build:
            context: src
            dockerfile: AAD/Dockerfile
        environment:
            MICROSOFT_GRAPH_CLIENT_ID: ${AAD_MICROSOFT_GRAPH_CLIENT_ID}
            MICROSOFT_GRAPH_AUTHORITY: ${AAD_MICROSOFT_GRAPH_AUTHORITY}
            MICROSOFT_GRAPH_APP_KEY: ${AAD_MICROSOFT_GRAPH_APP_KEY}
    teaching-server:
        build:
            context: src
            dockerfile: Teaching.Server/Dockerfile
        depends_on:
            - wake-up-computer
            - sokrates
            - photo-library
            - aad
    management-server:
        build:
            context: src
            dockerfile: Management.Server/Dockerfile
        depends_on:
            - sokrates
            - untis
            - final-theses
            - aad
