$env:DOTNET_ROOT=Split-Path -Parent (scoop which dotnet)
$env:ASPNETCORE_ENVIRONMENT="Development"
$env:SISDB_CONNECTION_STRING="Server=localhost;Port=8081;Database=sis2;User=root;Password=1234"
$env:SSL_CERT_PATH="$pwd\test\ssl\cert.pfx"
$env:SSL_CERT_PASSWORD="1234"
$env:BASE_DIRECTORIES="X:;$PSScriptRoot\testX;Y:;$PSScriptRoot\testY"
$env:TEACHER_IMAGE_DIR="$PSScriptRoot\test\teacher-images"
$env:MICROSOFT_GRAPH_CLIENT_ID="9fb9b79b-6e66-4007-a94f-571d7e3b68c5"
$env:MICROSOFT_GRAPH_TENANT_ID="81de7086-f6b3-4e4b-9faf-18d4a406e66d"
$env:MICROSOFT_GRAPH_APP_KEY=""
$env:MICROSOFT_GRAPH_AUTHORITY="https://login.microsoftonline.com/htlvb.at/"
$env:MICROSOFT_GRAPH_USERNAME="admin@htlvb.at"
$env:MICROSOFT_GRAPH_PASSWORD=""
$env:WEBUNTIS_BASE_URL="https://neilo.webuntis.com/WebUntis/"
$env:WEBUNTIS_SCHOOL_NAME="HTL_Vöcklabruck"
$env:WEBUNTIS_USERNAME="sisd"
$env:WEBUNTIS_PASSWORD=""
. .\set-secrets.ps1
