// <auto-generated/>
#pragma warning disable CS0618
using Keycloak.AdminApi.Admin.Realms.Item.ClientScopes.Item.ProtocolMappers.Protocol.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Keycloak.AdminApi.Admin.Realms.Item.ClientScopes.Item.ProtocolMappers.Protocol
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\realms\{realm}\client-scopes\{client-scope-id}\protocol-mappers\protocol
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProtocolRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Keycloak.AdminApi.admin.realms.item.clientScopes.item.protocolMappers.protocol.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Keycloak.AdminApi.Admin.Realms.Item.ClientScopes.Item.ProtocolMappers.Protocol.Item.WithProtocolItemRequestBuilder"/></returns>
        public global::Keycloak.AdminApi.Admin.Realms.Item.ClientScopes.Item.ProtocolMappers.Protocol.Item.WithProtocolItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("protocol", position);
                return new global::Keycloak.AdminApi.Admin.Realms.Item.ClientScopes.Item.ProtocolMappers.Protocol.Item.WithProtocolItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Keycloak.AdminApi.Admin.Realms.Item.ClientScopes.Item.ProtocolMappers.Protocol.ProtocolRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProtocolRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/realms/{realm}/client-scopes/{client%2Dscope%2Did}/protocol-mappers/protocol", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Keycloak.AdminApi.Admin.Realms.Item.ClientScopes.Item.ProtocolMappers.Protocol.ProtocolRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProtocolRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/realms/{realm}/client-scopes/{client%2Dscope%2Did}/protocol-mappers/protocol", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
